FROM alpine:3.21 as build

WORKDIR /var/www/html/

RUN apk add --no-cache zip unzip curl sqlite nginx supervisor \
    && apk add bash \
    && sed -i 's/bin\/ash/bin\/bash/g' /etc/passwd \
    && apk add --no-cache  \
    php82 php82-common php82-fpm php82-pdo php82-opcache php82-zip php82-phar php82-iconv php82-cli php82-curl php82-openssl php82-mbstring php82-tokenizer php82-fileinfo php82-json php82-xml php82-xmlwriter php82-simplexml php82-dom php82-pgsql php82-pdo_pgsql php82-pdo_sqlite php82-tokenizer php82-pecl-redis \
    && rm /etc/nginx/http.d/default.conf \
    && rm -rf /var/cache/apk/ \
    && ln -s /usr/bin/php82 /usr/bin/php \
    && curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm -rf composer-setup.php  \
    && mkdir -p /etc/supervisor.d/ \
    && mkdir -p /run/php/ \
    && touch /run/php/php8.2-fpm.pid \
    && mkdir -p /run/nginx/ \
    && touch /run/nginx/nginx.pid

COPY ./docker/supervisord.ini /etc/supervisor.d/supervisord.ini
COPY ./docker/php-fpm.conf /etc/php82/php-fpm.conf
COPY ./docker/php.ini-production /etc/php82/php.ini
COPY ./docker/nginx.conf /etc/nginx/
COPY ./docker/nginx-laravel.conf /etc/nginx/modules/

FROM alpine:3.21 as production

COPY --from=build /run/nginx /run/nginx
COPY --from=build /run/php /run/php
COPY --from=build /usr/bin/zip /usr/bin/zip

#COPY --from=build /etc/supervisor.conf /etc/supervisor.conf
COPY --from=build /etc/supervisor.d /etc/supervisor.d
COPY --from=build /usr/bin/echo_supervisord_conf /usr/bin/echo_supervisord_conf
COPY --from=build /usr/bin/supervisorctl /usr/bin/supervisorctl
COPY --from=build /usr/bin/supervisord /usr/bin/supervisord

COPY --from=build /usr/bin/phar.phar82 /usr/bin/phar.phar82
COPY --from=build /etc/php82 /etc/php82
COPY --from=build /usr/bin/php82 /usr/bin/php82
#COPY --from=build /usr/bin/php82/php /usr/bin/php82/php
COPY --from=build /usr/include/php82 /usr/include/php82
COPY --from=build /usr/sbin/php-fpm82 /usr/sbin/php-fpm82
COPY --from=build /usr/share/php82 /usr/share/php82
#COPY --from=build /usr/lib/php82 /usr/lib/php82

COPY --from=build /etc/nginx /etc/nginx
COPY --from=build /usr/sbin/nginx /usr/sbin/nginx
COPY --from=build /usr/share/nginx /usr/share/nginx
#COPY --from=build /usr/lib/nginx /usr/lib/nginx
COPY --from=build /usr/lib /usr/lib

RUN set -e && \
    mkdir -p /var/www/html /var/lib/nginx/logs \
    && mkdir /var/log/nginx \
    && touch /var/log/nginx/access.log \
    && touch /var/log/nginx/error.log \
    && touch /var/lib/nginx/logs/error.log \
    && ln -s /usr/bin/php82 /usr/bin/php

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log
RUN adduser -D vivek -u 1001
COPY ./html .
RUN chown -R vivek:vivek /var/www/html
RUN chown -R vivek:vivek /var/lib/nginx
RUN chown vivek:vivek /run/php/php8.2-fpm.pid
RUN chown vivek:vivek /run/nginx/nginx.pid
RUN chown vivek:vivek /var/lib/nginx/logs/error.log

EXPOSE 80

COPY ./app_deploy.sh /var/www/app_deploy.sh
RUN ["chmod", "+x", "/var/www/app_deploy.sh"]
#USER vivek
CMD [ "sh", "/var/www/app_deploy.sh" ]